### PR TITLE
Fix to allow multiple amazon bots and increase login delay

### PR DESCRIPTION
**Pull request by ysawa0**
After #124 if you tried to run a 2nd instance of the amz bot, you'd encounter this error as the user data dir being used is not unique and already in use
```
  File "nvidia-bot/cli/cli.py", line 85, in amazon
    amzn_obj = Amazon(
  File "nvidia-bot/stores/amazon.py", line 27, in __init__
    self.driver = webdriver.Chrome(executable_path=binary_path, options=options)

    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir
```
This fix gives each item url a different user data dir to allow multiple bots running at once

Also Amazon will send SMS texts sometimes asking the user to confirm the login initiated by the bot. Increase delay to 15 sec so the user has time to confirm the login manually otherwise login will not succeed.

### CODE REVIEW

**Review by freejack — CHANGES_REQUESTED** [review]
Might want to drop sleep back to 5 seconds.

**Comment by ysawa0** [comment]
@freejack I added the 15 sec delay as 5 sec is not enough time to accept the "confirm your login" prompts sent via sms, email, etc

**Review by Hari-Nagarajan — APPROVED** [review]
LGTM

**Review by freejack — APPROVED** [review]
Tested and confirmed multiple instances and autobuy works.

**Comment by ysawa0** [comment]
Thanks! If someone could merge it for me that'd be great as it needs 2 maintainer approvals looks like.

**Pull request merged**
