### PR TITLE
feat: Speed up autobuy checkout on nvidia.

### PR DESCRIPTION
**Pull request by Hari-Nagarajan**
Changed up nvidia auto checkout to use the APIs for almost everything. We are very close to full auto checkout with API only. Video of it in action: https://youtu.be/om8eRJtElL8

### CODE REVIEW

**Comment by mike9011** [comment]
Great work! Thanks! I'm going to test it in a couple of hours.

**Comment by mike9011** [comment]
I have an error when testing the 2060S:

```
INFO: "2020-09-21 08:50:15,487 - Checking if item (5336533500) in stock
INFO: "2020-09-21 08:50:15,597 - Error: [{'relation': 'https://developers.digitalriver.com/v1/shoppers/CartsResource', 'code': 'inventory-unavailable-error', 'description': 'Het spijt ons, maar NVIDIA GEFORCE RTX 2060 SUPER is momenteel niet in voorraad en kan niet aan uw winkelwagen worden toegevoegd. Wij bieden onze excuses aan voor het ongemak.'}]
```

translation of error string:
We're sorry, but NVIDIA GEFORCE RTX 2060 SUPER is currently out of stock and cannot be added to your cart. We apologize for the inconvenience. "}

**Comment by Hari-Nagarajan** [comment]
> I have an error when testing the 2060S:
> 
> ```
> INFO: "2020-09-21 08:50:15,487 - Checking if item (5336533500) in stock
> INFO: "2020-09-21 08:50:15,597 - Error: [{'relation': 'https://developers.digitalriver.com/v1/shoppers/CartsResource', 'code': 'inventory-unavailable-error', 'description': 'Het spijt ons, maar NVIDIA GEFORCE RTX 2060 SUPER is momenteel niet in voorraad en kan niet aan uw winkelwagen worden toegevoegd. Wij bieden onze excuses aan voor het ongemak.'}]
> ```
> 
> translation of error string:
> We're sorry, but NVIDIA GEFORCE RTX 2060 SUPER is currently out of stock and cannot be added to your cart. We apologize for the inconvenience. "}

Yeah thats the expected output when the item isnt in stock, let it keep running.

**Comment by mike9011** [comment]
> > I have an error when testing the 2060S:
> > ```
> > INFO: "2020-09-21 08:50:15,487 - Checking if item (5336533500) in stock
> > INFO: "2020-09-21 08:50:15,597 - Error: [{'relation': 'https://developers.digitalriver.com/v1/shoppers/CartsResource', 'code': 'inventory-unavailable-error', 'description': 'Het spijt ons, maar NVIDIA GEFORCE RTX 2060 SUPER is momenteel niet in voorraad en kan niet aan uw winkelwagen worden toegevoegd. Wij bieden onze excuses aan voor het ongemak.'}]
> > ```
> > 
> > 
> > translation of error string:
> > We're sorry, but NVIDIA GEFORCE RTX 2060 SUPER is currently out of stock and cannot be added to your cart. We apologize for the inconvenience. "}
> 
> Yeah thats the expected output when the item isnt in stock, let it keep running.

Yes, but the 2060S is in stock at the moment..

**Comment by Hari-Nagarajan** [comment]
> > > I have an error when testing the 2060S:
> > > ```
> > > INFO: "2020-09-21 08:50:15,487 - Checking if item (5336533500) in stock
> > > INFO: "2020-09-21 08:50:15,597 - Error: [{'relation': 'https://developers.digitalriver.com/v1/shoppers/CartsResource', 'code': 'inventory-unavailable-error', 'description': 'Het spijt ons, maar NVIDIA GEFORCE RTX 2060 SUPER is momenteel niet in voorraad en kan niet aan uw winkelwagen worden toegevoegd. Wij bieden onze excuses aan voor het ongemak.'}]
> > > ```
> > > 
> > > 
> > > translation of error string:
> > > We're sorry, but NVIDIA GEFORCE RTX 2060 SUPER is currently out of stock and cannot be added to your cart. We apologize for the inconvenience. "}
> > 
> > 
> > Yeah thats the expected output when the item isnt in stock, let it keep running.
> 
> Yes, but the 2060S is in stock at the moment..

This is where that output comes from:
```
        elif response.status_code == 409:
            log.info(f"Error: {response_json['errors']['error']}")
```
This is just the output from the api when I try to add that product ID to cart, are there multiple product IDs in your locale? I may have introduced a bug with locales, lets wait for @mihaiparvu to get eyes on this.

**Comment by gregoiredelzongle** [comment]
It should be related with #21 as it detect two 2060S for some reasons

**Comment by Hari-Nagarajan** [comment]
> It should be related with #21 as it detect two 2060S for some reasons

There are 2 2060s in the us locale because there are 2 2060s in the product api, so we have to check for both. The searches run on (mostly) independent threads so thats why you see a couple calls go through checking stock while you are checking out the one thats in stock, but all the threads stop after one successfully checks out.

**Comment by mike9011** [comment]
> > It should be related with #21 as it detect two 2060S for some reasons
> 
> There are 2 2060s in the us locale because there are 2 2060s in the product api, so we have to check for both. The searches run on (mostly) independent threads so thats why you see a couple calls go through checking stock while you are checking out the one thats in stock, but all the threads stop after one successfully checks out.

Just to add; I'm using the locale nl_nl

**Comment by mike9011** [comment]
@gregoiredelzongle On which step does it needs to end when autobuy is false? On the shopping cart page with the saved CC as payment method?

**Comment by mike9011** [comment]
When testing the 3080, it can't find a product id for locale nl_nl

`"2020-09-21 09:53:32,252 - We have no product IDs for NVIDIA GEFORCE RTX 3080, retrying until we get a product ID`

**Comment by gregoiredelzongle** [comment]
@Hari-Nagarajan Don't you think the "full_autobuy" set to false should put the user in the last validation page ? That is the behavior with the main branch.

**Comment by gregoiredelzongle** [comment]
`selenium_utils.wait_for_page(
            self.driver, "NVIDIA Online Store - Checkout")
)`
this probably mess with non en_US users

**Comment by mike9011** [comment]
> `selenium_utils.wait_for_page( self.driver, "NVIDIA Online Store - Checkout") )`
> this probably mess with non en_US users

This probably applies to all 'hardcoded' titles.

```
               "NVIDIA Online Store - Verify Order"
                "NVIDIA Online Store - Address Validation Suggestion Page"
```

**Comment by gregoiredelzongle** [comment]
```
File "/Users/gregoiredelzongle/Documents/GitHub/nvidia-bot/stores/nvidia.py", line 215, in run_items
    log.info(fut.result())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/gregoiredelzongle/Documents/GitHub/nvidia-bot/stores/nvidia.py", line 223, in buy
    while not self.add_to_cart(product_id) and self.enabled:
  File "/Users/gregoiredelzongle/Documents/GitHub/nvidia-bot/stores/nvidia.py", line 311, in add_to_cart
    response_json = response.json()
  File "/Users/gregoiredelzongle/.local/share/virtualenvs/nvidia-bot-JrMhpFct/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
after running it for one hour

**Comment by mike9011** [comment]
> ```
> File "/Users/gregoiredelzongle/Documents/GitHub/nvidia-bot/stores/nvidia.py", line 215, in run_items
>     log.info(fut.result())
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 432, in result
>     return self.__get_result()
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
>     raise self._exception
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/Users/gregoiredelzongle/Documents/GitHub/nvidia-bot/stores/nvidia.py", line 223, in buy
>     while not self.add_to_cart(product_id) and self.enabled:
>   File "/Users/gregoiredelzongle/Documents/GitHub/nvidia-bot/stores/nvidia.py", line 311, in add_to_cart
>     response_json = response.json()
>   File "/Users/gregoiredelzongle/.local/share/virtualenvs/nvidia-bot-JrMhpFct/lib/python3.8/site-packages/requests/models.py", line 898, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
>     return _default_decoder.decode(s)
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```
> 
> after running it for one hour

Yes, same issue here now after running it for 10 minutes.

**Comment by mihaiparvu** [comment]
> This is just the output from the api when I try to add that product ID to cart, are there multiple product IDs in your locale? I may have introduced a bug with locales, lets wait for @mihaiparvu to get eyes on this.

Looks good to me. No bug on locales part.

**Comment by darek292** [comment]
Just an FYI, if Nvidia were to cancel bot pre-orders, this would be the easiest way of knowing it was semi-automated with the use of API that isn't used on their website.

**Comment by gregoiredelzongle** [comment]
We'll see if we will be able to buy a card this way or not, but IMO they don't care of your buying method they just care about fraud. Rest is only PR

**Comment by darek292** [comment]
Yep, probably right, I think it's more to prevent scalpers. Most people here just want one card, unfortunately though if this information is already public then no doubt scalpers will have machines pulling on a continuous non-delayed loop to fetch them again (which I think they did last time too).

**Comment by Hari-Nagarajan** [comment]
> > ```
> > File "/Users/gregoiredelzongle/Documents/GitHub/nvidia-bot/stores/nvidia.py", line 215, in run_items
> >     log.info(fut.result())
> >   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 432, in result
> >     return self.__get_result()
> >   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
> >     raise self._exception
> >   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
> >     result = self.fn(*self.args, **self.kwargs)
> >   File "/Users/gregoiredelzongle/Documents/GitHub/nvidia-bot/stores/nvidia.py", line 223, in buy
> >     while not self.add_to_cart(product_id) and self.enabled:
> >   File "/Users/gregoiredelzongle/Documents/GitHub/nvidia-bot/stores/nvidia.py", line 311, in add_to_cart
> >     response_json = response.json()
> >   File "/Users/gregoiredelzongle/.local/share/virtualenvs/nvidia-bot-JrMhpFct/lib/python3.8/site-packages/requests/models.py", line 898, in json
> >     return complexjson.loads(self.text, **kwargs)
> >   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
> >     return _default_decoder.decode(s)
> >   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
> >     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> >   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
> >     raise JSONDecodeError("Expecting value", s, err.value) from None
> > json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> > ```
> > 
> > 
> > after running it for one hour
> 
> Yes, same issue here now after running it for 10 minutes.

I didn't run into this during my overnight run but I'll add a catch for JSONDecodeError on that API call.

**Pull request merged**
