### PR TITLE
Update nvidia_product_ids.json

### PR DESCRIPTION
**Pull request by BlueKingMuch**
added 3080 de_de and de_at (both have different ID) 
added 3090 for de_de and de_at (both have same ID)

proofs:
https://api-prod.nvidia.com/direct-sales-shop/DR/products/de_de/EUR/5440853700
https://api-prod.nvidia.com/direct-sales-shop/DR/products/de_de/EUR/5438792300
https://api-prod.nvidia.com/direct-sales-shop/DR/products/de_de/EUR/5438761400

### CODE REVIEW

**Comment by jzyrobert** [comment]
How were you able to find the IDs? I've been trying to get them for en_gb

**Comment by BlueKingMuch** [comment]
> 
> 
> How were you able to find the IDs? I've been trying to get them for en_gb

back when nVidia's digitalriver public api-key worked, you could search for all products and eventually find the digitalRiver ID.

i can recommend to watch this commit from another git: https://github.com/jef/nvidia-snatcher/issues/161

there should be also en_gb

**Comment by iKreateCode** [comment]
> > How were you able to find the IDs? I've been trying to get them for en_gb
> 
> back when nVidia's digitalriver public api-key worked, you could search for all products and eventually find the digitalRiver ID.
> 
> i can recommend to watch this commit from another git: [jef/nvidia-snatcher#161](https://github.com/jef/nvidia-snatcher/issues/161)
> 
> there should be also en_gb
> 
> edit: it's 5438792800 for en_gb
> 
> proof:
> https://api-prod.nvidia.com/direct-sales-shop/DR/products/en_GB/USD/5438792800

using that link gives empty and that product is for 3080 only when you change USD to GBP

**Comment by BlueKingMuch** [comment]
> 
> 
> > > How were you able to find the IDs? I've been trying to get them for en_gb
> > 
> > 
> > back when nVidia's digitalriver public api-key worked, you could search for all products and eventually find the digitalRiver ID.
> > i can recommend to watch this commit from another git: [jef/nvidia-snatcher#161](https://github.com/jef/nvidia-snatcher/issues/161)
> > there should be also en_gb
> > edit: it's 5438792800 for en_gb
> > proof:
> > https://api-prod.nvidia.com/direct-sales-shop/DR/products/en_GB/USD/5438792800
> 
> using that link and product code is for 3080 only

correct.

**Comment by iKreateCode** [comment]
> How were you able to find the IDs? I've been trying to get them for en_gb

Yeah mee

> > > > How were you able to find the IDs? I've been trying to get them for en_gb
> > > 
> > > 
> > > back when nVidia's digitalriver public api-key worked, you could search for all products and eventually find the digitalRiver ID.
> > > i can recommend to watch this commit from another git: [jef/nvidia-snatcher#161](https://github.com/jef/nvidia-snatcher/issues/161)
> > > there should be also en_gb
> > > edit: it's 5438792800 for en_gb
> > > proof:
> > > https://api-prod.nvidia.com/direct-sales-shop/DR/products/en_GB/USD/5438792800
> > 
> > 
> > using that link and product code is for 3080 only
> 
> correct. i don't have any other ID's for en_gb

Im after 3090 en_gb codes

**Comment by dn00** [comment]
Found this list for en-us. Tried some codes following the apparent pattern but nothing for 3090. It might not even be up yet for US. Which would be a good move by nvidia.

[https://gist.github.com/jef/96fd50c6fe3eedc1bdf52585eac2b3c4#gistcomment-3458430](https://gist.github.com/jef/96fd50c6fe3eedc1bdf52585eac2b3c4#gistcomment-3458430)

**Review by Hari-Nagarajan — APPROVED** [review]
LGTM

**Pull request merged**
