### PR TITLE
Added background update function to compare local HEAD and remote HEA…

### PR DESCRIPTION
**Pull request by worst-mod-confirmed**
…D, if they don't match notify the user to update every 10 mins.

### CODE REVIEW

**Review by Hari-Nagarajan — DISMISSED** [review]

**Review by Hari-Nagarajan — DISMISSED** [review]

**Comment by WillsB3** [comment]
Great idea but I'm not sure on the approach. What happens for users who have not used git to clone the repo and have just downloaded the zip from github?

Would it be simpler to setup a github action that updates a text file in the repo root with the git hash of the last commit*? With this approach we could just make a http request for the file at `https://raw.githubusercontent.com/Hari-Nagarajan/nvidia-bot/master/version`, pull the hash out of it and then compare it with the hash inside the `version` file on disk. Saves adding dependencies and works for both people using git or "Download Zip".

_*Obviously the hash in this file will always be one commit behind true HEAD, because we won't know what the commit hash of the commit updating the manifest file will be until the commit has occured…_

**Review by WillsB3 — COMMENTED** [review]
Great idea but I'm not sure on the approach. What happens for users who have not used git to clone the repo and have just downloaded the zip from github?

Would it be simpler to setup a github action that updates a text file in the repo root with the git hash of the last commit*? With this approach we could just make a http request for the file at `https://raw.githubusercontent.com/Hari-Nagarajan/nvidia-bot/master/version`, pull the hash out of it and then compare it with the hash inside the `version` file on disk. Saves adding dependencies and works for both people using git or "Download Zip".

_*Obviously the hash in this file will always be one commit behind true HEAD, because we won't know what the commit hash of the commit updating the manifest file will be until the commit has occured…_

**Comment by worst-mod-confirmed** [comment]
That's a possible solution but it would be somewhat of a nightmare with multiple PR's merging in on top of direct work on the repo. Since we can't be clairvoyant and see the future commit, it would be a pain to have to double commit with each PR, and it's likely to get forgotten as we move from one issue/feature to the next. Another possible solution is to not use the git hash and rather read from some form of versioning file from the master branch that increments with each PR much like the tagging system works, or just switch to tags all together.

**Comment by Hari-Nagarajan** [comment]
We could have a version file that gets bumped only on major changes

**Comment by geekyed** [comment]
Yer I’d prefer it if we used something like semver. Only incrementing on the master branch.

**Pull request closed without merging**
