### PR TITLE
Amazon.it Support

### PR DESCRIPTION
**Pull request by SuperSamy**
Hi, I tried but unfortunately I see that it is not compatible with Amazon.it, it is the only missing store, you could add it, it would be really nice! Thank you so much Hari!

### CODE REVIEW

**Comment by WillsB3** [comment]
Hi

We need some page title strings to add support for Amazon.it. Take a look at https://github.com/Hari-Nagarajan/nvidia-bot/blob/master/stores/amazon.py#L29-L73 and see if you can provide the exact page titles required.

Thanks

**Comment by WillsB3** [comment]
Sorry. Just seen that this is a pull request…

Are you sure you filed this PR correctly? You appear to have raised it for an unrelated branch?

Have you made code changes you want to get reviewed and merged or was this PR meant to be an issue?

**Comment by SuperSamy** [comment]
> Sorry. Just seen that this is a pull request…
> 
> Are you sure you filed this PR correctly? You appear to have raised it for an unrelated branch?
> 
> Have you made code changes you want to get reviewed and merged or was this PR meant to be an issue?

Actually I have seen now that I have the wrong branch, where should I make the request?

**Review by WillsB3 — CHANGES_REQUESTED** [review]
This PR appears to be for a branch unrelated to adding Amazon.it support.

Was this Pull Request made in error?

**Comment by WillsB3** [comment]
@SuperSamy You will need to make a fork of this repository to your own GitHub account, make the changes in your fork, and then raise a PR from your fork to this repository. 

If that's out of your comfort zone feel free to just provide us the page title strings and we can handle updating th code 👍

**Comment by SuperSamy** [comment]
> @SuperSamy Dovrai creare un fork di questo repository sul tuo account GitHub, apportare le modifiche nel tuo fork e quindi sollevare un PR dal tuo fork a questo repository.
> 
> Se questo è fuori dalla tua zona di comfort, sentiti libero di fornirci solo le stringhe del titolo della pagina e possiamo gestire l'aggiornamento del codice 👍

Ok thanks, I'm trying to find the titles of amazon.it

**Comment by SuperSamy** [comment]
> @SuperSamy Dovrai creare un fork di questo repository sul tuo account GitHub, apportare le modifiche nel tuo fork e quindi sollevare un PR dal tuo fork a questo repository.
> 
> Se questo è fuori dalla tua zona di comfort, sentiti libero di fornirci solo le stringhe del titolo della pagina e possiamo gestire l'aggiornamento del codice 👍

> SIGN_IN_TITLES = ["Amazon Sign In", "Amazon Sign-In", "Amazon Anmelden", "Il mio account - Amazon.it", "Accedi"]
CAPTCHA_PAGE_TITLES = ["Robot Check"]
HOME_PAGE_TITLES = [
    "Amazon.com: Online Shopping for Electronics, Apparel, Computers, Books, DVDs & more",
    "Amazon.ca: Low Prices – Fast Shipping – Millions of Items",
    "Amazon.co.uk: Low Prices in Electronics, Books, Sports Equipment & more",
    "Amazon.de: Low Prices in Electronics, Books, Sports Equipment & more",
    "Amazon.de: Günstige Preise für Elektronik & Foto, Filme, Musik, Bücher, Games, Spielzeug & mehr",
    "Amazon.es: compra online de electrónica, libros, deporte, hogar, moda y mucho más.",
    "Amazon.de: Günstige Preise für Elektronik & Foto, Filme, Musik, Bücher, Games, Spielzeug & mehr",
    "Amazon.fr : livres, DVD, jeux vidéo, musique, high-tech, informatique, jouets, vêtements, chaussures, sport, bricolage, maison, beauté, puériculture, épicerie et plus encore !",
    "Amazon.it: elettronica, libri, musica, fashion, videogiochi, DVD e tanto altro",
]
SHOPING_CART_TITLES = [
    "Amazon.com Shopping Cart",
    "Amazon.ca Shopping Cart",
    "Amazon.co.uk Shopping Basket",
    "Amazon.de Basket",
    "Amazon.de Einkaufswagen",
    "Cesta de compra Amazon.es",
    "Amazon.fr Panier",
    "Carrello Amazon.it",
]
CHECKOUT_TITLES = [
    "Amazon.com Checkout",
    "Place Your Order - Amazon.ca Checkout",
    "Place Your Order - Amazon.co.uk Checkout",
    "Amazon.de Checkout",
    "Place Your Order - Amazon.de Checkout",
    "Amazon.de - Bezahlvorgang",
    "Place Your Order - Amazon.com Checkout",
    "Place Your Order - Amazon.com",
    "Tramitar pedido en Amazon.es",
    "Processus de paiement Amazon.com",
    "Procedi all'acquisto",
    "Procedi all'ordine",
    "Acquista ora",
]
ORDER_COMPLETE_TITLES = [
    "Amazon.com Thanks You",
    "Amazon.ca Thanks You",
    "Thank you",
    "Amazon.fr Merci",
    "Merci",
    "Grazie, il tuo ordine è stato ricevuto",
    "Grazie",
]
ADD_TO_CART_TITLES = [
    "Amazon.com: Please Confirm Your Action",
    "Amazon.de: Bitte bestätigen Sie Ihre Aktion",
    "Amazon.de: Please Confirm Your Action",
    "Amazon.es: confirma tu acción",
    "Amazon.com : Veuillez confirmer votre action",  # Careful, required non-breaking space after .com (&nbsp)
    "Amazon.it: conferma la tua azione",
]

I entered the Amazon titles, I send them here because I can't make my own repo.

**Comment by SuperSamy** [comment]
> @SuperSamy You will need to make a fork of this repository to your own GitHub account, make the changes in your fork, and then raise a PR from your fork to this repository.
>
>If that's out of your comfort zone feel free to just provide us the page title strings and we can handle updating the code 👍

Hi, I found the strings for Amazon.it, I tried to start the bot and it works, but it crashes at the last step, when I have to click "Buy Now". I just miss this, could you fix this? Many thanks in advance.

Missing string: CHECKOUT_TITLES (Place Order)

Strings for Amazon.it are:

> SIGN_IN_TITLES = ["Amazon Sign In", "Amazon Sign-In", "Amazon Anmelden", "Il mio account - Amazon.it", "Accedi"]
CAPTCHA_PAGE_TITLES = ["Robot Check"]
HOME_PAGE_TITLES = [
    "Amazon.com: Online Shopping for Electronics, Apparel, Computers, Books, DVDs & more",
    "Amazon.ca: Low Prices – Fast Shipping – Millions of Items",
    "Amazon.co.uk: Low Prices in Electronics, Books, Sports Equipment & more",
    "Amazon.de: Low Prices in Electronics, Books, Sports Equipment & more",
    "Amazon.de: Günstige Preise für Elektronik & Foto, Filme, Musik, Bücher, Games, Spielzeug & mehr",
    "Amazon.es: compra online de electrónica, libros, deporte, hogar, moda y mucho más.",
    "Amazon.de: Günstige Preise für Elektronik & Foto, Filme, Musik, Bücher, Games, Spielzeug & mehr",
    "Amazon.fr : livres, DVD, jeux vidéo, musique, high-tech, informatique, jouets, vêtements, chaussures, sport, bricolage, maison, beauté, puériculture, épicerie et plus encore !",
    "Amazon.it: elettronica, libri, musica, fashion, videogiochi, DVD e tanto altro",
]
SHOPING_CART_TITLES = [
    "Amazon.com Shopping Cart",
    "Amazon.ca Shopping Cart",
    "Amazon.co.uk Shopping Basket",
    "Amazon.de Basket",
    "Amazon.de Einkaufswagen",
    "Cesta de compra Amazon.es",
    "Amazon.fr Panier",
    "Carrello Amazon.it",
]
CHECKOUT_TITLES = [
    "Amazon.com Checkout",
    "Place Your Order - Amazon.ca Checkout",
    "Place Your Order - Amazon.co.uk Checkout",
    "Amazon.de Checkout",
    "Place Your Order - Amazon.de Checkout",
    "Amazon.de - Bezahlvorgang",
    "Place Your Order - Amazon.com Checkout",
    "Place Your Order - Amazon.com",
    "Tramitar pedido en Amazon.es",
    "Processus de paiement Amazon.com",
]
ORDER_COMPLETE_TITLES = [
    "Amazon.com Thanks You",
    "Amazon.ca Thanks You",
    "Thank you",
    "Amazon.fr Merci",
    "Merci",
    "Grazie da Amazon.it",
]
ADD_TO_CART_TITLES = [
    "Amazon.com: Please Confirm Your Action",
    "Amazon.de: Bitte bestätigen Sie Ihre Aktion",
    "Amazon.de: Please Confirm Your Action",
    "Amazon.es: confirma tu acción",
    "Amazon.com : Veuillez confirmer votre action",  # Careful, required non-breaking space after .com (&nbsp)
    "Amazon.it: confermare l'operazione",

last2
last

**Comment by WillsB3** [comment]
You appear to be missing the title for `CHECKOUT_TITLES` which would likely be the cause of this crash

**Comment by SuperSamy** [comment]
> You appear to be missing the title for CHECKOUT_TITLES which would likely be the cause of this crash

Yes, I know, in fact I wrote it before, could you tell me where it is? I can't find it at all, couldn't you complete the last missing string?

**Comment by WillsB3** [comment]
It's in your screenshot :). Look at the tab title. Go to that page and `View`->`Source` then copy the title from the `<title>` tag

**Comment by WillsB3** [comment]
Once you've done that, find an ASIN for a cheap in stock item and rerun the bot with `python app.py amazon --test`. It should add the in stock item to the cart and proceed to the checkout. It will stop just before placing the order and it will auto close the browser and you will see something along the lines of `Order placed` in your terminal. If you see that it means it works 👍

**Comment by SuperSamy** [comment]
> It's in your screenshot :). Look at the tab title. Go to that page and `View`->`Source` then copy the title from the `<title>` tag

Perfect! It worked! Thanks! A question, I'm also trying on Amazon.de, but the screen to select the address and payment method comes out, how can I go directly to the checkout page (Submit order)?

amz de
amz de2

**Comment by SuperSamy** [comment]
image

**Comment by SuperSamy** [comment]
> @SuperSamy I'm not 100% sure but you may need to setup 1-click ordering on your Aamazon.de account. Let me know if that works.
> 
> Could you submit a pull request or just here in a comment the final list of strings you needed to get Amazon.it working please? Thanks :)
> 
> P.S. I've removed the screenshot from your comment as it contains some personal info which I think you won't want to keep here.

Ok thanks a lot, I will create a pool, in the meantime I try with 1 click

**Comment by SuperSamy** [comment]
> @SuperSamy I'm not 100% sure but you may need to setup 1-click ordering on your Aamazon.de account. Let me know if that works.
> 
> Could you submit a pull request or just here in a comment the final list of strings you needed to get Amazon.it working please? Thanks :)
> 
> P.S. I've removed the screenshot from your comment as it contains some personal info which I think you won't want to keep here.

Amazon.it Strings:

> SIGN_IN_TITLES = ["Amazon Sign In", "Amazon Sign-In", "Amazon Anmelden", "Il mio account - Amazon.it", "Amazon Accedi"]
CAPTCHA_PAGE_TITLES = ["Robot Check"]
HOME_PAGE_TITLES = [
    "Amazon.com: Online Shopping for Electronics, Apparel, Computers, Books, DVDs & more",
    "Amazon.ca: Low Prices – Fast Shipping – Millions of Items",
    "Amazon.co.uk: Low Prices in Electronics, Books, Sports Equipment & more",
    "Amazon.de: Low Prices in Electronics, Books, Sports Equipment & more",
    "Amazon.de: Günstige Preise für Elektronik & Foto, Filme, Musik, Bücher, Games, Spielzeug & mehr",
    "Amazon.es: compra online de electrónica, libros, deporte, hogar, moda y mucho más.",
    "Amazon.de: Günstige Preise für Elektronik & Foto, Filme, Musik, Bücher, Games, Spielzeug & mehr",
    "Amazon.fr : livres, DVD, jeux vidéo, musique, high-tech, informatique, jouets, vêtements, chaussures, sport, bricolage, maison, beauté, puériculture, épicerie et plus encore !",
    "Amazon.it: elettronica, libri, musica, fashion, videogiochi, DVD e tanto altro",
]
SHOPING_CART_TITLES = [
    "Amazon.com Shopping Cart",
    "Amazon.ca Shopping Cart",
    "Amazon.co.uk Shopping Basket",
    "Amazon.de Basket",
    "Amazon.de Einkaufswagen",
    "Cesta de compra Amazon.es",
    "Amazon.fr Panier",
    "Carrello Amazon.it",
]
CHECKOUT_TITLES = [
    "Amazon.com Checkout",
    "Place Your Order - Amazon.ca Checkout",
    "Place Your Order - Amazon.co.uk Checkout",
    "Amazon.de Checkout",
    "Place Your Order - Amazon.de Checkout",
    "Amazon.de - Bezahlvorgang",
    "Place Your Order - Amazon.com Checkout",
    "Place Your Order - Amazon.com",
    "Tramitar pedido en Amazon.es",
    "Processus de paiement Amazon.com",
    "Pagamento Amazon.it",
    "Preparing your order",
    "Select a delivery address",
]
ORDER_COMPLETE_TITLES = [
    "Amazon.com Thanks You",
    "Amazon.ca Thanks You",
    "Thank you",
    "Amazon.fr Merci",
    "Merci",
    "Grazie da Amazon.it",
]
ADD_TO_CART_TITLES = [
    "Amazon.com: Please Confirm Your Action",
    "Amazon.de: Bitte bestätigen Sie Ihre Aktion",
    "Amazon.de: Please Confirm Your Action",
    "Amazon.es: confirma tu acción",
    "Amazon.com : Veuillez confirmer votre action",  # Careful, required non-breaking space after .com (&nbsp)
    "Amazon.it: confermare l'operazione",
]

**Comment by Hari-Nagarajan** [comment]
This is good but this PR will merge changes from the apprise branch that are not yet ready to merge into master. Need to hold off on this.

**Comment by SuperSamy** [comment]
> This is good but this PR will merge changes from the apprise branch that are not yet ready to merge into master. Need to hold off on this.

Unfortunately I don't know how to do more than this: /

**Review by Hari-Nagarajan — APPROVED** [review]

**Pull request merged**
