### PR TITLE
Auto checkout system

### PR DESCRIPTION
**Pull request by gregoiredelzongle**
Barebone auto-checkout system using Selenium, not pretty but it works

User have to create beforehand a Nvidia store account with infos (address, street etc.... ) already saved in.
The script also re-enter your credit card info because it does not save the CVV code when you order a card.

To make it work : create a autobuy_config.json
{
  "NVIDIA_LOGIN": "your@login.com",
  "NVIDIA_PASSWORD": "password",
  "FULL_AUTOBUY":true, # will validate your order if true, if false you have to click the last button
  "CREDITCARD_NUMBER":"4263982640269299", #your credit card infos
  "CREDITCARD_EXP":"02/2023", #your CC expiration date
  "CREDITCARD_SECURITY_CODE":"837" #CCV
  "AUTOBUY_COUNTRY_SELECT":"" #Leave it like that except if you have to set explicitely your country in the Nvidia Store
}

It will need a little bit of refactoring and a clever way to click the "next" and "submit" button instead of getting it by it's value
Also updating the docs

### CODE REVIEW

**Comment by gregoiredelzongle** [comment]
I used this to test in order to not accidently buy a 2060S
https://developers.bluesnap.com/docs/test-credit-cards

**Comment by Hari-Nagarajan** [comment]
Hey, what region did you test this in? I'd like some international users  to try it out as well before we merge it.

**Comment by zuliwa** [comment]
I can test for de_de if needed

**Comment by gregoiredelzongle** [comment]
> 
> 
> I used this to test in order to not accidently buy a 2060S
> https://developers.bluesnap.com/docs/test-credit-cards

fr_fr

**Comment by gregoiredelzongle** [comment]
You should be able to go through the auto-checkout system from multiple countries now

**Comment by mike9011** [comment]
Can you safely test this with a non-existing CC number when you already have a CC saved in your Nvidia account?

**Comment by gregoiredelzongle** [comment]
Yes ! It enters a new CC number info, if you want to be safe you can set FULL_AUTOBUY to false to avoid clicking the final button

**Comment by mike9011** [comment]
I will test it tomorrow morning for nl_nl.

**Comment by zuliwa** [comment]
This person has an auto checkout system that (apparently) works.
They're on the discord too
https://github.com/DLSteve/nvidia-bot

**Comment by gregoiredelzongle** [comment]
yes it seems less convoluted than this method we should try to checkout like DLSteve does !

**Comment by mike9011** [comment]
It's working for nl_nl, great! However, i'm not sure how it will behave when the servers are flooded.

**Comment by johnconnor2020** [comment]
> This person has an auto checkout system that (apparently) works.
> They're on the discord too
> https://github.com/DLSteve/nvidia-bot
> This may end up being a useful resource

How do I activate his bot?

**Comment by johnconnor2020** [comment]
> You should be able to go through the auto-checkout system from multiple countries now

What do I type in for Germany?
 ` "AUTOBUY_COUNTRY_SELECT":"de_de"`
 ?

**Comment by gregoiredelzongle** [comment]
leave it empty, just "" ! this variables is for several countries (UK,Canada) who get some additional prompts after login

**Comment by johnconnor2020** [comment]
> leave it empty, just "" ! this variables is for several countries (UK,Canada) who get some additional prompts after login

Ah gotcha! Thanks for this awesome tool.

**Review by Hari-Nagarajan — APPROVED** [review]

**Pull request merged**
