### PR TITLE
feat: Add headless flag support

### PR DESCRIPTION
**Pull request by mihaiparvu**
Added a new cli flag `--headless`. Also ditched selenium's `chrome_options` in favor of `options`. I tested on `nvidia.py`, don't really know the others. If you review this PR please test the other stores as well.

### CODE REVIEW

**Comment by Hari-Nagarajan** [comment]
Works on amazon.com

**Comment by Hari-Nagarajan** [comment]
Works on Nvidia and Amazon, no point testing evga as evga has captcha on log in.

**Comment by mihaiparvu** [comment]
What about BestBuy?

**Comment by Hari-Nagarajan** [comment]
Best buy's auto buy isn't enabled right now, so the selenium stuff in there isn't currently used. Its just auto cart.

**Comment by mihaiparvu** [comment]
Ok, I'll revert the BB and EVGA files for minimal code changes

**Comment by Hari-Nagarajan** [comment]
> Ok, I'll revert the BB and EVGA files for minimal code changes

Leave it as is I would say

**Review by Hari-Nagarajan — APPROVED** [review]
LGTM

**Pull request merged**
