### PR TITLE
Notification on script crash.

### PR DESCRIPTION
**Pull request by geekyed**

### CODE REVIEW

**Review by WillsB3 — CHANGES_REQUESTED** [review]
Thanks for the contribution @geekyed!

As discussed offline, let's define this behaviour in a new decorator, e.g. `@notify_on_crash` as this will allow us keep avoid some of the repetition.

Let me know if you need a hand 👍

**Comment by geekyed** [comment]
Not sure if there is a better place to put the decorator, this is my first go at python 😀

**Review by Hari-Nagarajan — APPROVED** [review]
LGTM

**Review by WillsB3 — APPROVED** [review]
Nice one - this looks good to me.

Thanks for the PR 👍

**Pull request merged**
