### PR TITLE
Evga support for cards and series

### PR DESCRIPTION
**Pull request by BennettStaley**
you can now add series, 3090, or 3080 to your config. as well as P/N numbers for card selection. It will navigate to the specific card page and refresh it.

Now has readme adjustments

### CODE REVIEW

**Comment by BennettStaley** [comment]
Once i get some feedback i'll squash these into one commit.

**Comment by Hari-Nagarajan** [comment]
Can you pull from master? These changes conflict with https://github.com/Hari-Nagarajan/nvidia-bot/pull/102

**Comment by BennettStaley** [comment]
@Hari-Nagarajan done. also added a refresh routine for pages that don't match the title we are looking for.

(when requesting the 3090 chipset we end up getting sent back to index)

**Comment by BennettStaley** [comment]
working as intended: 3080:
image

3090:
image

**Comment by Hari-Nagarajan** [comment]
It looks good, but I cant run this. Can anyone else confirm as well?

**Comment by BennettStaley** [comment]
You cant run it? What do you mean? @Hari-Nagarajan

**Comment by Hari-Nagarajan** [comment]
> You cant run it? What do you mean? @Hari-Nagarajan

My EVGA acc is completely locked

**Comment by BennettStaley** [comment]
Should i be worried about this as well?

**Comment by Hari-Nagarajan** [comment]
> Should i be worried about this as well?

I tested dozens of purchases using privacy.com $1 cards. I'm not sure what exactly gets your account locked, but this may have something to do with it.

**Comment by Hari-Nagarajan** [comment]
Some user's on github verified that this works.

**Review by Hari-Nagarajan — APPROVED** [review]
LGTM

**Pull request merged**
