### PR TITLE
Walmart bot

### PR DESCRIPTION
**Pull request by agmeadows**
Working Walmart bot for U.S. site. Nearly working 2captcha integration to solve ReCaptcha V2

### CODE REVIEW

**Comment by R1fast** [comment]
Thanks for sharing this @agmeadows.  Is the CIV the card security # on the stored CC?

**Comment by agmeadows** [comment]
> 
> 
> Thanks for sharing this @agmeadows. Is the CIV the card security # on the stored CC?

Yes, it is the 3 digit code on the back of the card. I found when you add you billing information into Walmart it asks you to confirm the CIV card before completing the order.

**Comment by R1fast** [comment]
Cool thanks... would love to help test but I'm stumbling on getting this to work -- I'm a python newbie.  I tried cloning your PR to my local branch which looked ok but I didn't see the walmart store when running python app.py.  I also tried a total rip/reinstall instead using your master repo @ https://github.com/agmeadows/nvidia-bot but same result (amazon, bestbuy show but no walmart).  

Am I missing something obvious or maybe I just need to get better at python first :|

**Comment by agmeadows** [comment]
> 
> 
> Cool thanks... would love to help test but I'm stumbling on getting this to work -- I'm a python newbie. I tried cloning your PR to my local branch which looked ok but I didn't see the walmart store when running python app.py. I also tried a total rip/reinstall instead using your master repo @ https://github.com/agmeadows/nvidia-bot but same result (amazon, bestbuy show but no walmart).
> 
> Am I missing something obvious or maybe I just need to get better at python first :|

I am new to GitHub so I may not have done something correct. I was running the script by using this command: python app.py walmart. You just need the walmart.py file in the stores folder and the Walmart .json in the root directory.

**Comment by R1fast** [comment]
Hmm - okay I definitely have both of those but get an error of "no such command walmart" when running **python app.py walmart**.   I'll mess around w/it some more to see if I can get it working - hopefully the PR gets merged soon enough either way.

image

image

**Comment by agmeadows** [comment]
I forgot that I edited cli.py to add the Walmart bot. I just uploaded it. Give that a try and see what happens

**Comment by R1fast** [comment]
Progress - it's now recognized by app.py  but kicks back this error:  _module 'utils.selenium_utils' has no attribute 'yes_walmart_image'_

image

**Comment by fm407** [comment]
you have to add these in utils/selenium_utils.py....

`def no_walmart_image():
    prefs = {"profile.managed_default_content_settings.images": 2}
    options.add_experimental_option("prefs", prefs)


def yes_walmart_image():
    prefs = {"profile.managed_default_content_settings.images": 0}
    options.add_experimental_option("prefs", prefs)
`

**Comment by agmeadows** [comment]
Ah yes, I forgot I modified that file to. I am new to Git Hub and just started monkeying with files. I forgot which ones I modified. I didn't to upload all of my files because it is a hot mess.

**Comment by R1fast** [comment]
Aaaand closer.  Now selenium opens but crashes w/this error:

image

**Comment by agmeadows** [comment]
That looks correct to me. This is what mine looks like:
image
I am not sure what the issue would be

**Comment by R1fast** [comment]
> That looks correct to me. This is what mine looks like
> image
> I am not sure what the issue would be

Yeah - no idea what could be wrong at this point since I uninstalled everything in Documents/Github, users/xx/.virtualenvs and appdata python folders, then reinstalled using your master.    Shoot... not sure what else to try - hopefully someone else can chime in.

**Comment by fm407** [comment]
add import json to walmart.py, not sure why that was removed

**Comment by DakkJaniels** [comment]
I made a walmart branch, can you please PR on to that for testing. Also just let GitHub upload all the changed files, rather than picking them. It should not upload the config.json files, those are set to ignore.

**Comment by agmeadows** [comment]
Good catch @fm407 I am not sure how that happened. I was cleaning up the file and must have deleted that on accident or didn't copy it.

**Comment by agmeadows** [comment]
> I made a walmart branch, can you please PR on to that for testing. Also just let GitHub upload all the changed files, rather than picking them. It should not upload the config.json files, those are set to ignore.

I am not quite sure how to do a new pull request on that branch. Do I need to close this one?

**Comment by DakkJaniels** [comment]
I swapped it to the walmart branch already. Are you using github desktop? I find it's easier to do all this stuff that way. If you aren't, someone else might be able to tell you the CLI commands to push your files on to it. With github desktop, I think I just changed my branch, and then it asks if I want to associated my changed files with that branch - then say yes and commit the files (more or less, I don't have GitHub desktop open at the moment).

**Comment by R1fast** [comment]
@DakkJaniels (or anyone who knows really) How would we go about updating our pipenv with the walmart branch?  Do we just clone that branch and follow the standard steps?

**Comment by flaviiio** [comment]
would love to add Walmart but man do I not understand much of what is said. I will need so much help

**Comment by agmeadows** [comment]
@DakkJaniels I think I have a new pull request under the walmart branch. 

@R1fast When I was making any changes I needed to make sure I was out of pipenv. Any changes that were made with that active happened in the virtual environment. I also ran pipenv shell and pipenv install again at some point. I am not sure which fixed the problem.

**Review by charleylee — COMMENTED** [review]
Getting this with latest:
`2020-11-24 18:08:58 DESKTOP-BF0JVON nvidia-bot[9760] INFO Testing XPath
2020-11-24 18:08:58 DESKTOP-BF0JVON nvidia-bot[9760] INFO Found price $499.00
$499.00
2020-11-24 18:08:58 DESKTOP-BF0JVON nvidia-bot[9760] INFO Product not available
2020-11-24 18:08:58 DESKTOP-BF0JVON nvidia-bot[9760] INFO Checking stock for items.
Traceback (most recent call last):
  File "app.py", line 5, in <module>
    cli.main()
  File "C:\Users\civic\.virtualenvs\nvidia-bot-walmart-idgZAKdR\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\civic\.virtualenvs\nvidia-bot-walmart-idgZAKdR\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\civic\.virtualenvs\nvidia-bot-walmart-idgZAKdR\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\civic\.virtualenvs\nvidia-bot-walmart-idgZAKdR\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\civic\.virtualenvs\nvidia-bot-walmart-idgZAKdR\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\git\nvidia-bot-walmart\cli\cli.py", line 28, in decorator
    func(*args, **kwargs)
  File "C:\git\nvidia-bot-walmart\cli\cli.py", line 108, in walmart
    walmrt_obj.run_item(test=test)
  File "C:\git\nvidia-bot-walmart\stores\walmart.py", line 184, in run_item
    checkout_success = self.check_stock(url, self.reserve[i])
  File "C:\git\nvidia-bot-walmart\stores\walmart.py", line 226, in check_stock
    self.check_stock(url, reserve)
  File "C:\git\nvidia-bot-walmart\stores\walmart.py", line 226, in check_stock
    self.check_stock(url, reserve)
  File "C:\git\nvidia-bot-walmart\stores\walmart.py", line 226, in check_stock
    self.check_stock(url, reserve)
  [Previous line repeated 90 more times]
  File "C:\git\nvidia-bot-walmart\stores\walmart.py", line 214, in check_stock
    self.check_captcha(url)
  File "C:\git\nvidia-bot-walmart\stores\walmart.py", line 208, in check_captcha
    self.defeat_captcha(self.driver.current_url)
  File "C:\git\nvidia-bot-walmart\stores\walmart.py", line 291, in defeat_captcha
    captcha_id = s.post(
IndexError: list index out of range
`
any ideas what it might be?

**Comment by agmeadows** [comment]
That error is in the captcha check. Walmart probably hit you with a Captcha window. The Captcha solve isn't really working at the moment. Comment out the defeat_captcha function and change check_captcha to:

```
def check_captcha(self, url):
        while self.driver.title in CAPTCHA_URL:
            log.info("Please manually solve Captcha")
            sleep(5)
```

You will have to manually solve the captcha and the script should continue on

**Comment by agmeadows** [comment]
Closing this pull as it is now out dated by the new branch

**Comment by fm407** [comment]
> That error is in the captcha check. Walmart probably hit you with a Captcha window. The Captcha solve isn't really working at the moment. Comment out the defeat_captcha function and change check_captcha to:
> 
> ```
> def check_captcha(self, url):
>         while self.driver.title in CAPTCHA_URL:
>             log.info("Please manually solve Captcha")
>             sleep(5)
> ```
> 
> You will have to manually solve the captcha and the script should continue on

hey man, have you checked this: https://stackoverflow.com/questions/53688300/2captcha-api-selenium

**Comment by agmeadows** [comment]
> 
> 
> > That error is in the captcha check. Walmart probably hit you with a Captcha window. The Captcha solve isn't really working at the moment. Comment out the defeat_captcha function and change check_captcha to:
> > ```
> > def check_captcha(self, url):
> >         while self.driver.title in CAPTCHA_URL:
> >             log.info("Please manually solve Captcha")
> >             sleep(5)
> > ```
> > 
> > 
> > You will have to manually solve the captcha and the script should continue on
> 
> hey man, have you checked this: https://stackoverflow.com/questions/53688300/2captcha-api-selenium

I have been working with 2captcha to work around the verification. For all the people that complain about bots on Walmart, they don't realize how sophisticated their system is compared to others. Walmart tracks your clicks on the page to verify you are human and they won't let you click the audio button if they believe you are a bot. I submitted my 2captcha code to another user on the 2captcha forum and it worked to defeat the ReCaptcha they were stuck on.

**Pull request closed without merging**
